feat: [LM2-351] add support for single tenancy envs
dividohq/finance-plugin-woocommerce pull request #79
Opened 2021-08-17 13:59 UTC by dmontag23

This PR adds an "Environment URL" field to the Woocommerce settings page where the user can enter in the URL of the environment they want to point to.

This field is defaulted from the pre-existing api key to ensure backwards compatibility. If the api key does not exist, the field will default to a blank value.

These changes have been tested using both the Divido sandbox multi-tenant env and the ING UAT env.

2021-08-18 11:51 UTC, dafuloth submitted a review, later dismissed

2021-08-19 09:33 UTC, USilviuDvdo commented on class-wc-gateway-finance.php
> +            $environment = \Divido\MerchantSDK\Environment::getEnvironmentFromAPIKey($this->api_key);
Can we set the environment as a class attribute also and reuse it, just like we do with the url above instead of calling `getEnvironmentFromAPIKey` everywhere? Something like:

`$this->environment = \Divido\MerchantSDK\Environment::getEnvironmentFromAPIKey($this->api_key);` -> on line  119.

2021-08-19 09:34 UTC, USilviuDvdo commented on class-wc-gateway-finance.php
> +            $env = \Divido\MerchantSDK\Environment::getEnvironmentFromAPIKey($api_key);
Do you understand why $this->api_key is not used here? Is there  a logical explanation or an issue with the original code ?

2021-08-19 10:08 UTC, nunocosta-divido commented on class-wc-gateway-finance.php
> +            $env = \Divido\MerchantSDK\Environment::getEnvironmentFromAPIKey($api_key);
I believe it is because the function where this code was inserted accepts `$api_key` as a parameter.

I'm also of the view that, fas a rule of thumb, if a function needs a parameter then it should be passed to it, as it makes the function stateless and their dependencies explicit

2021-08-19 10:08 UTC, nunocosta-divido commented on class-wc-gateway-finance.php
> +            $environment = \Divido\MerchantSDK\Environment::getEnvironmentFromAPIKey($this->api_key);
👍

2021-08-19 10:19 UTC, dmontag23 commented on class-wc-gateway-finance.php
> +            $environment = \Divido\MerchantSDK\Environment::getEnvironmentFromAPIKey($this->api_key);
@USilviuDvdo Good suggestion - I'll make that change.

2021-08-19 11:24 UTC, andivido requested changes
The translations issue probably needs to be addressed. The rest are just refinement suggestions, so feel free to mark resolved as you see fit

2021-08-19 11:24 UTC, andivido commented on class-wc-gateway-finance.php
> +        function get_default_tenant_env($api_key)
Is the method name a bit misleading, as we're getting the merchant-api-pub url for the environment, rather than the environment itself

2021-08-19 11:24 UTC, andivido commented on class-wc-gateway-finance.php
> +            $environment = \Divido\MerchantSDK\Environment::getEnvironmentFromAPIKey($this->api_key);
Can you:
`use \Divido\MerchantSDK\Environment;`
at the top of the file so you can just use Environment:: in the code?
To be fair Environment is kinda vague, so I quite like the use of the full namespace. Ignore this comment!

2021-08-19 11:24 UTC, andivido commented on class-wc-gateway-finance.php
>              $httpClientWrapper = new \Divido\MerchantSDK\HttpClient\HttpClientWrapper(
Makes sense to actually have a getSDK function since we are using this same code on multiple occasions. Would be good to make it a singleton too whilst doing this, though I don't think there's a case in the code where we'd make the ClientWrapper twice

2021-08-19 11:24 UTC, andivido commented on class-wc-gateway-finance.php
>                  $this->api_key
We're using the $api_key and $this->api_key in this method. Should probably get rid of the least reliable one

2021-08-19 11:24 UTC, andivido commented on class-wc-gateway-finance.php
> +                    'title' => __('backend/configenvironment_url_label', 'woocommerce-finance-gateway'),
The translations for this only appear to be in English in poeditor. Let me know if you want me to show you how to add them in different languages

2021-08-23 09:21 UTC, dmontag23 commented on class-wc-gateway-finance.php
> +        function get_default_tenant_env($api_key)
@andivido I agree, it is misleading. What do you think about `get_default_merchant_api_pub_url`?

2021-08-23 13:07 UTC, dmontag23 commented
@andivido @nunocosta-divido @USilviuDvdo I updated this PR with your suggestions. There were a fair number of changes, so would you mind reviewing the PR again? Thanks!

2021-08-24 08:39 UTC, freddieline approved these changes
Very nice! Good job with the singleton class to instantiate the sdk and adding the translations.

2021-08-24 08:39 UTC, andivido approved these changes
This looks great

2021-08-24 08:45 UTC, USilviuDvdo approved these changes

2021-08-24 08:54 UTC, freddieline requested changes
Please can you update the plugin version number and add to the changelog

2021-08-24 08:59 UTC, freddieline approved these changes

2021-08-24 08:59 UTC, merged