Fix/mer 36 lightbox display
dividohq/finance-plugin-woocommerce pull request #92
Opened 2021-10-29 15:43 UTC by dbelkad

### PR CHECKLIST

- [x] All translations are concatenated with an EOT character between the translation context and key (ie. `backend/config[EOT]general_settings_header`)
- [x] The version information documented in the readme.txt has been manually updated in line with semantic versioning
- [x] The version information in `class-wc-gateway-finance.php` (included within the initial docblock and the start of the constructor) has been updated

2021-11-03 12:57 UTC, joelbitar requested changes
Need to check for empty values as before.

2021-11-03 12:57 UTC, joelbitar commented on class-wc-gateway-finance.php
> +            $this->widget_threshold = (null !== $this->settings['widgetThreshold']) ? $this->settings['widgetThreshold'] : 250;
This will break further down the line since if the settings is empty we are stuck with an empty string here.

We also need to check if it an empty string, only contains spaces, maby it is weirdly formatted like " 123"

I would suggest that we check if it is "0", then fine. 0 it is.
If it is not "0" we try and parse it to an int, that means empty, spaces and weirdness will be cast into a 0, we can then default that to 250. What do you think?

2021-11-03 14:46 UTC, andivido commented on class-wc-gateway-finance.php
> +            $this->widget_threshold = (null !== $this->settings['widgetThreshold']) ? $this->settings['widgetThreshold'] : 250;
@joelbitar : I think the issue at the moment _is that_ we check for an empty value. This code should have been designed to set default values initially, not every time we load the config. If the customer has specifically set the widget threshold (the lower bound product price for the widget to show on a product page) to empty (baring in mind this code will set the default value to 250, so they'd have to delete that default 250), they'd expect there to be no widget threshold, and for the calculator to display regardless of the product price.
Hence the check for !== null, ie. isset(), so that we only set a default value if $this->settings['widgetThreshold'] doesn't exist; ie. the first time this code is run.
Agree with further validation, but I think maybe that should be happening when we're saving the value, rather than checking what is saved

2021-11-03 14:56 UTC, andivido commented on class-wc-gateway-finance.php
> +            $this->widget_threshold = (null !== $this->settings['widgetThreshold']) ? $this->settings['widgetThreshold'] : 250;
Actually, have I got it wrong with isset and !== null being equivalent? It should be `isset()` I think

2021-11-05 10:58 UTC, joelbitar requested changes
Great stuff! We now need to update version number and release it / test it

2021-11-05 11:09 UTC, joelbitar approved these changes

2021-11-08 11:23 UTC, merged