fix: added SKU to the products array
dividohq/finance-plugin-woocommerce pull request #94
Opened 2021-11-04 16:18 UTC by dbelkad

### PR CHECKLIST

- [ ] All translations are concatenated with an EOT character between the translation context and key (ie. `backend/config[EOT]general_settings_header`)
- [ ] The version information documented in the readme.txt has been manually updated in line with semantic versioning
- [ ] The readme file's Changelog has been updated with your proposed PR
- [ ] The version information in `class-wc-gateway-finance.php` (included within the initial docblock and the start of the constructor) has been updated

2021-11-08 10:45 UTC, andivido commented on class-wc-gateway-finance.php
> +                print_r($products);exit;
```suggestion
                
```

2021-11-08 10:51 UTC, andivido commented on class-wc-gateway-finance.php
> +                if ($this->is_available($product) && $price > (((int)$this->widget_threshold ?? 0) * 100)) {
Just need to make sure we don't overwrite our other PR

2021-11-08 10:54 UTC, andivido requested changes
Looks good. Just need to remove the die dump. Try to put formatting changes in a separate commit, so it's easier to see what material changes were carried out

2021-11-08 11:32 UTC, dbelkad commented on class-wc-gateway-finance.php
> +                if ($this->is_available($product) && $price > (((int)$this->widget_threshold ?? 0) * 100)) {
It shouldn't. And if there is a conflict, I'll fix it before merging the PR.

2021-11-12 16:51 UTC, andivido approved these changes

2021-11-12 16:53 UTC, andivido requested changes

2021-11-12 16:53 UTC, andivido commented on readme.txt
> +Version:           2.3.3
These need to be bumped to 2.3.4 now

2021-11-12 16:53 UTC, andivido commented on readme.txt
> +
you seemed to have lost the changelog for 2.3.3 somewhere

2021-11-15 08:12 UTC, joelbitar commented on readme.txt
> -=== Plugin Name ===
Why is the entire file marked as updated, seems weird to me...

2021-11-15 08:16 UTC, joelbitar requested changes
We should try to avoid to change formatting when we don't need to. Makes it a lot harder to follow along and what changes actually matter, accidentally introducing new bugs.
Could we try to just change the lines that needs changing?

2021-11-15 09:43 UTC, dbelkad commented on readme.txt
> +
I worked on the fix for the cart threshold where you can see the changes in log to 2.3.3. This was another task, hence the another bump as the PR hasn't been merged yet.

2021-11-15 09:44 UTC, dbelkad commented on readme.txt
> -=== Plugin Name ===
I'm sorry about the re-formatting. It's a bad habit of mine. I'll revert the changes.

2021-11-15 12:02 UTC, closed without merging