fix: Adjusted the way we set values to the config fields.
dividohq/finance-plugin-woocommerce pull request #97
Opened 2021-11-15 12:09 UTC by dbelkad

### PR CHECKLIST

- [ ] All translations are concatenated with an EOT character between the translation context and key (ie. `backend/config[EOT]general_settings_header`)
- [ ] The version information documented in the readme.txt has been manually updated in line with semantic versioning
- [ ] The readme file's Changelog has been updated with your proposed PR
- [ ] The version information in `class-wc-gateway-finance.php` (included within the initial docblock and the start of the constructor) has been updated

2021-11-15 12:53 UTC, andivido reviewed
I'd put this in draft then rebase this to master when https://github.com/dividohq/finance-plugin-woocommerce/pull/96 is merged, so that people don't accidentally merge the later PR first

2021-11-23 21:36 UTC, andivido commented on class-wc-gateway-finance.php
> +            $this->cart_threshold = isset($this->settings['cartThreshold']) && $this->settings['cartThreshold'] !== '' ? $this->settings['cartThreshold'] : 250;
The `&& $this->settings['cartThreshold'] !== '' ` part still doesn't make sense to me. If the merchant leaves the field blank then it will set it to the default value, which doesn't make sense to me

2021-11-24 10:36 UTC, dbelkad commented on class-wc-gateway-finance.php
> +            $this->cart_threshold = isset($this->settings['cartThreshold']) && $this->settings['cartThreshold'] !== '' ? $this->settings['cartThreshold'] : 250;
This has now been purged and the input is being parsed into an integer.

2021-11-24 10:47 UTC, andivido requested changes

2021-11-24 10:47 UTC, andivido commented on class-wc-gateway-finance.php
> +            echo '<pre>';var_dump($this->widget_threshold);exit;
Get rid of this!

2021-11-24 10:51 UTC, dbelkad commented on class-wc-gateway-finance.php
> +            echo '<pre>';var_dump($this->widget_threshold);exit;
I did it again!!!! Soz! :(

2021-11-25 11:49 UTC, andivido requested changes
I'd squash and merge.

I'd try to avoid merging like https://github.com/dividohq/finance-plugin-woocommerce/pull/97/commits/9bac951dbf5ca4de14e114052882830d910de922 in the future, so as to avoid having changes from other PRs included in unrelated PRs

2021-11-25 11:49 UTC, andivido commented on class-wc-gateway-finance.php
> + * Version: 2.3.4
```suggestion
 * Version: 2.3.5
```

2021-11-25 11:49 UTC, andivido commented on class-wc-gateway-finance.php
> +            $this->plugin_version = '2.3.4';
```suggestion
            $this->plugin_version = '2.3.5';
```

2021-11-25 13:05 UTC, andivido approved these changes
Nice force push 💪 Looks much better
Looks good!

2021-11-25 15:05 UTC, merged